on:
  push:
    tags:
      - "v*"
name: GoReleaser
jobs:
  release:
    name: Release
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@master
      - name: releaser
        uses: docker://jerson/goreleaser:0.118
        env:
          GITHUB_TOKEN: ${{ secrets.GLOBAL_GITHUB_TOKEN }}
        with:
          args: release
        if: success()
